version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kp"
s3_bucket = "kp-noahhome"
s3_prefix = "kp"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
